job:
  name: model
  tags: {"env": "dev"}
  default_cluster_node_type_id: Standard_DS3_v2
  git_url: https://github.com/lexara-prime-ai/DATABRICKS_CDD.git
  git_branch: "feature/model"
  git_commit: "Created/Updated feature/model"
  git_tag:
  tasks:
    - task_key: feature
      description: model/feature
      python_file: feature.py
      parameters: ["feature"]
    - task_key: model_scoring
      description: model_scoring.py
      parameters: ["scoring"]
      depends_on: ["feature"]